using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Text.Json;
using AutoFlow.Application.Interfaces;

namespace AutoFlow.Infrastructure.Localization;

public class JsonLocalizationService : ILocalizationService, INotifyPropertyChanged
{
    public event PropertyChangedEventHandler? PropertyChanged;

    private Dictionary<string, string> _translations = new();
    private string _currentCulture = "pt-BR";
    private readonly string _basePath;

    public string this[string key] => GetString(key);

    public JsonLocalizationService()
    {
        _basePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Assets", "i18n");
        if (!Directory.Exists(_basePath)) Directory.CreateDirectory(_basePath);
        
        LoadTranslations();
    }

    public string GetString(string key)
    {
        return _translations.TryGetValue(key, out var value) ? value : key;
    }

    public void SetLanguage(string cultureCode)
    {
        if (string.IsNullOrEmpty(cultureCode)) cultureCode = "pt-BR";
        _currentCulture = cultureCode;
        LoadTranslations();
        // O indexador  uma propriedade especial chamada "Item"
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Item"));
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Item[]"));
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(null)); // Notifica tudo
    }

    private void LoadTranslations()
    {
        var filePath = Path.Combine(_basePath, $"{_currentCulture}.json");
        var defaults = GetDefaults(_currentCulture);

        if (File.Exists(filePath))
        {
            try
            {
                var json = File.ReadAllText(filePath);
                var loaded = JsonSerializer.Deserialize<Dictionary<string, string>>(json) ?? new();
                
                // Merge loaded with defaults to ensure new keys are present
                _translations = new Dictionary<string, string>(defaults);
                foreach (var kvp in loaded)
                {
                    _translations[kvp.Key] = kvp.Value;
                }
            }
            catch
            {
                _translations = defaults;
            }
        }
        else
        {
            _translations = defaults;
            SaveTranslations(filePath, _translations);
        }
    }

    private void SaveTranslations(string path, Dictionary<string, string> dict)
    {
        try
        {
            var json = JsonSerializer.Serialize(dict, new JsonSerializerOptions { WriteIndented = true });
            File.WriteAllText(path, json);
        }
        catch { }
    }

    private Dictionary<string, string> GetDefaults(string culture)
    {
        return culture switch
        {
            "en-US" => GetEnUsDefaults(),
            "es-ES" => GetEsEsDefaults(),
            "ja-JP" => GetJaJpDefaults(),
            "ru-RU" => GetRuRuDefaults(),
            _ => GetPtBrDefaults()
        };
    }

    private Dictionary<string, string> GetEnUsDefaults() => new() {
        ["Dashboard"] = "Dashboard", ["Jobs"] = "Flows", ["History"] = "Audit", ["Settings"] = "Settings", 
        ["Blueprint"] = "Blueprint", ["NewBlueprint"] = "New Blueprint", ["Flows"] = "Flows",
        ["Greeting"] = "Good evening!", ["ActiveAuto"] = "You have {0} active flows.",
        ["Total"] = "Total", ["Running"] = "Running", ["Completed"] = "Completed", ["Failed"] = "Failed",
        ["RecentActivity"] = "Recent Activity", ["QuickActions"] = "Quick Actions", ["ErrorAudit"] = "Error Audit",
        ["NewJob"] = "New Flow", ["NewAuto"] = "New Flow", ["ViewHistory"] = "View History",
        ["NoErrors"] = "No errors recorded.", ["OpenErrorFolder"] = "Open Error Folder", ["ClearLogs"] = "Clear Logs",
        ["SaveSettings"] = "Save Settings", ["Appearance"] = "Appearance", ["SystemTheme"] = "Theme", ["Language"] = "Language",
        ["Behavior"] = "Behavior", ["ShowNotifications"] = "Notifications", ["StartAtStartup"] = "Auto-start",
        ["Support"] = "Support", ["SupportDesc"] = "If AutoFlow is useful, support us!", ["BuyCoffee"] = "Buy Me a Coffee",
        ["Add"] = "Add", ["Hotfolder"] = "Hotfolder", ["Run"] = "Run", ["StopAll"] = "Stop All", ["Delete"] = "Delete",
        ["QueueManagement"] = "MANAGE OPERATION QUEUE", ["OpLog"] = "Operation Log", ["ManualOp"] = "Manual Operations", ["Automation"] = "Flows",
        ["HistoryHeader"] = "FLOW HISTORY", ["Update"] = "Update", ["SearchHistory"] = "Search files or destinations...",
        ["NoLogs"] = "No logs found.",
        ["Copy"] = "Copy", ["Move"] = "Move", ["Skip"] = "Skip", ["Overwrite"] = "Overwrite", ["Rename"] = "Rename",
        ["None"] = "None", ["Interval"] = "Interval", ["Daily"] = "Daily", ["Weekly"] = "Weekly",
        ["RealTime"] = "Real-Time", ["Polling"] = "Polling", ["OnSuccess"] = "On Success", ["OnError"] = "On Error", ["OnBoth"] = "On Both",
        ["ControlPanel"] = "Control Panel", ["SystemOverview"] = "System overview and metrics",
        ["Type"] = "Type:", ["Task"] = "Task:", ["SystemHealth"] = "SYSTEM HEALTH", ["TotalVolume"] = "TOTAL VOLUME",
        ["ProcessedData"] = "Processed data", ["TimeSaved"] = "TIME SAVED", ["AutomatedWork"] = "Automated work",
        ["Files"] = "FILES", ["DirectCopy"] = "Direct Flow", ["WatchFolder"] = "Active Flow", ["PauseAll"] = "Pause All",
        ["RecentActivities"] = "RECENT ACTIVITIES", ["UpcomingRadar"] = "SCHEDULE RADAR", ["SystemMonitor"] = "SYSTEM MONITOR",
        ["CopySpeed"] = "Flow Speed", ["Processor"] = "Processor (CPU)", ["Ram"] = "RAM Memory", ["CloudSync"] = "Cloud Sync",
        ["All"] = "All", ["Excellent"] = "Excellent", ["Good"] = "Good", ["Attention"] = "Attention", ["Critical"] = "Critical",
        ["NoData"] = "No data", ["Downloading"] = "Downloading...", ["Synced"] = "Synced", ["GlobalPaused"] = "Global processing paused.", ["GlobalResumed"] = "Global processing resumed.",
        ["AdvancedSettings"] = "Advanced Settings", ["SettingsDesc"] = "Full control over performance, integration and visuals",
        ["EnginePerformance"] = "ENGINE & PERFORMANCE", ["Parallelism"] = "Parallelism (Threads)", ["ParallelismDesc"] = "Number of files processed simultaneously",
        ["ProcessPriority"] = "Process Priority", ["PriorityDesc"] = "Software impact on Windows performance",
        ["GlobalBandwidth"] = "Global Bandwidth Limit", ["BandwidthDesc"] = "Limit copy speed to not saturate network (0 = Unlimited)",
        ["SecurityPrivacy"] = "SECURITY & PRIVACY", ["AccessPin"] = "Access PIN", ["PinWatermark"] = "Set a numeric PIN",
        ["PinDesc"] = "Protect interface with a password", ["LockOnMinimize"] = "Lock on minimize",
        ["EncryptionKey"] = "Master Encryption Key", ["EncryptionKeyWatermark"] = "Your global key", ["EncryptionDesc"] = "Suggested as default for new secure jobs",
        ["ExternalNotifications"] = "EXTERNAL NOTIFICATIONS (WEBHOOKS & SMTP)", ["WebhookUrl"] = "Webhook URL",
        ["WebhookUrlWatermark"] = "https://discord.com/api/webhooks/...", ["SmtpServer"] = "SMTP Server",
        ["SmtpHostWatermark"] = "smtp.gmail.com", ["Port"] = "Port", ["DestEmail"] = "Destination Email",
        ["DestEmailWatermark"] = "alerts@email.com", ["EnableSmtp"] = "Enable Email", ["NotifyOnSuccess"] = "Notify Success", ["NotifyOnError"] = "Notify Errors",
        ["AutomationSystem"] = "SYSTEM CONFIGURATION", ["StartWithWindows"] = "Start with Windows", ["StartWithWindowsDesc"] = "Open automatically on computer startup",
        ["CloseToTray"] = "Close to Tray (System Tray)", ["CloseToTrayDesc"] = "Keep AutoFlow running when closing main window",
        ["MaintenanceData"] = "MAINTENANCE & DATA", ["LogRetention"] = "Log Retention", ["LogRetentionDesc"] = "Days to keep records in history",
        ["DatabaseSize"] = "Size: {0}", ["ClearNow"] = "Clear Now", ["OptimizeDatabase"] = "Optimize Database",
        ["VisualLanguage"] = "VISUAL & LANGUAGE", ["InterfaceTheme"] = "Interface Theme", ["SystemLanguage"] = "System Language",
        ["GlassOpacity"] = "Glass Effect Opacity (Mica/Acrylic)", ["DiscardChanges"] = "Discard Changes",
        ["ConfigureAutomation"] = "Configure Flow", ["AutomationRules"] = "Define rules, filters and destinations",
        ["General"] = "General", ["Filters"] = "Filters", ["Schedule"] = "Schedule", ["Security"] = "Security", ["Advanced"] = "Advanced",
        ["JobName"] = "Flow Name", ["SourcePath"] = "Source Path", ["DestPath"] = "Destination Path", ["WorkMode"] = "Work Mode",
        ["FileConflicts"] = "File Conflicts", ["IncludeExtensions"] = "Include Extensions", ["IgnorePatterns"] = "Ignore Patterns",
        ["RegexExpression"] = "Regex Expression", ["WatcherConfigs"] = "WATCHER CONFIGS", ["DetectionMethod"] = "Detection Method",
        ["StabilizationTime"] = "Stabilization Time", ["ScheduleType"] = "Schedule Type", ["RepeatOnDays"] = "Repeat on days:",
        ["Sun"] = "S", ["Mon"] = "M", ["Tue"] = "T", ["Wed"] = "W", ["Thu"] = "T", ["Fri"] = "F", ["Sat"] = "S",
        ["ExecutionTime"] = "Execution Time", ["DataProtection"] = "DATA PROTECTION", ["EncryptionKeyLabel"] = "Encryption Key",
        ["JobWebhooks"] = "FLOW WEBHOOKS", ["SimulationSummary"] = "SIMULATION SUMMARY", ["FilesIdentified"] = "Files Identified",
        ["DataVolume"] = "Data Volume", ["SimulationSuccess"] = "Simulation completed successfully.",
        ["Simulate"] = "Simulate", ["NewDirectCopyTitle"] = "New Direct Flow", ["NewWatchFolderTitle"] = "New Active Flow",
        ["Save"] = "Save", ["Cancel"] = "Cancel", ["ProcessSubfolders"] = "Process Subfolders", ["SmartSyncLabel"] = "Smart Sync",
        ["VerifyHashLabel"] = "Verify Hash", ["ClearPreview"] = "Clear Preview", ["SaveAutomation"] = "Save Flow",
        ["AuditHistory"] = "Audit & History", ["ForenseTracking"] = "Forensic tracking of all operations",
        ["ExportCsv"] = "Export CSV", ["OpDetails"] = "OPERATION DETAILS", ["File"] = "File", ["Destination"] = "Destination",
        ["Size"] = "Size", ["Duration"] = "Duration", ["EngineLogs"] = "Engine Logs", ["SelectEntry"] = "Select an entry",
        ["SearchWatermark"] = "Search...", ["Time"] = "Time", ["Origin"] = "Origin", ["OpenSourceFolder"] = "Open Source Folder",
        ["OpenDestFolder"] = "Open Destination Folder", ["ClearHistory"] = "Clear History", ["Copied"] = "COPIED",
        ["Moved"] = "MOVED", ["Ignored"] = "IGNORED", ["FailedStatus"] = "FAILED", ["Zipped"] = "ZIPPED", ["Cancelled"] = "CANCELLED",
        ["SidebarAutomation"] = "Flows", ["SidebarAudit"] = "Audit", ["AutomationHub"] = "Flow Hub",
        ["ActiveBadge"] = "{0} Active", ["QueueReady"] = "Ready", ["AutomationDesc"] = "Manage your data flows",
        ["StopAllTip"] = "Terminate All", ["Active"] = "Active", ["Pending"] = "Pending", ["Watchers"] = "Watchers",
        ["SearchJobsWatermark"] = "Search flows...", ["SelectedCount"] = "{0} selected", ["RealTimeProcessing"] = "REAL-TIME",
        ["ConfiguredTasks"] = "YOUR FLOWS", ["RunTip"] = "Run", ["StopTip"] = "Stop", ["EditTip"] = "Edit", ["DeleteTip"] = "Delete",
        ["OriginLabel"] = "ORIGIN:", ["DestLabel"] = "DEST:", ["Frequency"] = "FREQUENCY", ["SpeedLabel"] = "SPEED", ["LiveTerminal"] = "TERMINAL",
        ["Processing"] = "Processing...", ["Idle"] = "Idle", ["Queued"] = "Queued...", ["NewDirectCopy"] = "New Direct Flow",
        ["NewWatchFolder"] = "New Active Flow", ["JobNameWatermark"] = "e.g. Backup", ["Browse"] = "Browse",
        ["ExtensionsWatermark"] = ".jpg, .png", ["IgnoreWatermark"] = "temp, node_modules", ["RegexWatermark"] = "^[0-9].*",
        ["OpenApp"] = "Open AutoFlow", ["Exit"] = "Exit", ["SuccessBadge"] = "OK", ["IgnoredBadge"] = "IGN", ["ErrorBadge"] = "ERR", ["SmtpEmailHeader"] = "SMTP / Email",
        ["JobStarted"] = "Flow '{0}' started.", ["RetryMode"] = " [RETRY]", ["PreScriptFailed"] = "Pre-script failed.",
        ["SourceNotFound"] = "Source not found: {0}", ["JobError"] = "Flow Error", ["JobFailedSourceNotFound"] = "Flow '{0}' failed: Source missing.",
        ["StartingFile"] = "Starting: {0}", ["SuccessFile"] = "Success: {0}", ["ErrorFile"] = "ERROR: {0}",
        ["FilterIgnored"] = "Filter ignored.", ["JobFinished"] = "Flow Finished: {0}", ["JobCompleted"] = "Flow Completed",
        ["FilesFailed"] = "{0} files failed.", ["UserCancelled"] = "Flow '{0}' cancelled.", ["UserCancelledOp"] = "Cancelled.",
        ["CriticalError"] = "Critical Error", ["CriticalErrorJob"] = "Error in '{0}': {1}", ["PostScriptFailed"] = "Post-script failed.",
        ["IntegrityFailed"] = "Integrity failed.", ["ZipCreationFailed"] = "ZIP failed: {0}",
        ["RetentionOldDeleted"] = "Retention: Deleted {0}", ["RetentionExpiredDeleted"] = "Retention: Expired {0}",
        ["RetentionFailed"] = "Retention failed: {0}", ["SmartSyncDetail"] = "SmartSync", ["StartingJobLog"] = "Starting Flow: {0}",
        ["PreviewErrorSourceNotFound"] = "Source missing: {0}", ["PreviewIgnored"] = "[SKIP] {0}",
        ["PreviewIgnoredSmartSync"] = "[SYNC] {0}", ["PreviewIgnoredConflict"] = "[CONFLICT] {0}",
        ["PreviewOverwrite"] = "[OVERWRITE] {0}", ["PreviewRename"] = "[RENAME] {0}", ["PreviewCopy"] = "[COPY] {0}", ["PreviewMove"] = "[MOVE] {0}",
        ["RamUsageFormat"] = "{0} GB / {1} GB", ["TimeSavedFormat"] = "{0}h {1}m", ["SchedulerLoopError"] = "Scheduler error: {0}",
        ["DailyMaintenanceSuccess"] = "Maintenance OK.", ["DailyMaintenanceError"] = "Maintenance error: {0}",
        ["DailySummaryName"] = "Daily Summary", ["InXDays"] = "in {0} days", ["InXHours"] = "in {0}h", ["InXMinutes"] = "in {0}min",
        ["SupportTitle"] = "Support the Developer", ["SupportPixLabel"] = "Pix Key (Brazil)", ["SupportCoffeeLabel"] = "Buy Me a Coffee", ["SupportCopyPix"] = "Copy Key",
        ["Donate"] = "Donate",
        ["NoWatchers"] = "No monitored folders found.",
        ["NoTransfers"] = "No direct flows configured.",
        ["NoIncidents"] = "No incidents recorded. Everything is running smoothly!",
        ["NoSystemLogs"] = "No system events recorded.",
        ["NoFileBlueprints"] = "No file organization models.",
        ["NoFolderBlueprints"] = "No folder structure models.",
        
        // Organization (Blueprint)
        ["Organization"] = "Blueprint",
        ["Scaffolding"] = "Structure",
        ["ScaffoldingDesc"] = "Create subfolders automatically",
        ["Renaming"] = "Smart Rename",
        ["RenamingDesc"] = "Standardize names using tokens",
        ["FolderBlueprint"] = "Folder Blueprint",
        ["FileOrganization"] = "File Organization",
        ["FolderStructure"] = "Folder Structure",
        ["NewFileBlueprint"] = "New File Blueprint",
        ["NewFolderBlueprint"] = "New Folder Blueprint",
        ["AddFolder"] = "Add Folder",
        ["RenameTemplateLabel"] = "Renaming Template",
        ["TokensAvailable"] = "Tokens: {Date}, {JobName}, {Counter}, {001}",
        ["TokensFolderDesc"] = "Special: {FolderName}, {Parent}, {Ano}, {Mes}",
        ["TokensFileDesc"] = "Special: {FileName}, {Ext}, {Date}",
        ["TokenOriginal"] = "Original Name",
        ["TokenParent"] = "Parent Folder",
        ["TokenDate"] = "Current Date",
        ["TokenYear"] = "Current Year",
        ["TokenMonth"] = "Current Month",
        ["TokenCounter"] = "Counter",
        ["Token001"] = "Counter (001)",
        ["TokenGuid"] = "Unique ID",
        ["PresetDate"] = "Date and Name",
        ["PresetCounter"] = "Sequential",
        ["PresetSnake"] = "Cleanup (snake_case)",
        ["BeforeAfter"] = "Transformation",
        ["InternalStructure"] = "Internal Structure (What to create inside?)",
        ["IdentityHeader"] = "Identity (How to rename?)",
        ["QuickStyles"] = "Quick Styles",
        ["MagicPresets"] = "Ready Sugestions",
        ["TokenDay"] = "Current Day",
        ["PresetCamel"] = "Programming (camelCase)",
        ["RegexRemoveNumbers"] = "Remove Numbers",
        ["RegexCleanSpecial"] = "Clean Special",
        ["RegexExtractDate"] = "Extract Date",
        ["InvalidChars"] = "Invalid Characters",
        ["ToolboxTokens"] = "Tokens",
        ["ToolboxStyles"] = "Styles",
        ["ToolboxRegex"] = "Regex",
        ["ToolboxCleanup"] = "Cleanup",
        ["RegexTutorial"] = "Regex: \\d (digit), \\w (word), [^abc] (not abc)",
        ["RegexTips"] = "Tips: ( ) creates groups, $1 uses the first group. Regex modifiers replace ALL occurrences by default.",
        ["RegexAdvancedHelp"] = "Regular Expressions allow complex manipulations:\n\n• GROUPS: Use ( ) to capture parts of the name.\n• BACK-REFERENCE: Use $1, $2 to reinsert captured parts.\n• QUANTIFIERS:\n  + (one or more times)\n  * (zero or more times)\n  ? (optional)\n• CLASSES:\n  \\d (any digit)\n  \\w (letters and numbers)\n  \\s (spaces)\n  . (any character)",
        ["StylesAdvancedHelp"] = "Identity Transformers:\n\n• CASE: Change to UPPERCASE, lowercase or Title Case.\n• PROGRAMMING: Convert to camelCase or snake_case for code compatibility.\n• CLEANING: Use ':clean' to remove special symbols and keep a 'pure' name.\n• SUBSTRINGS:\n  TAKE (get first N characters)\n  SKIP (skip first N characters)",
        ["OriginalPath"] = "ORIGIN",
        ["ResultPath"] = "DESTINATION",
        ["MagicTools"] = "MAGIC TOOLS",
        ["SmartToolbox"] = "SMART TOOLBOX",
        ["ConfigureCounter"] = "Configure Counter:",
        ["ZerosPadding"] = "Zeros (Padding)",
        ["InsertCounter"] = "Insert Counter",
        ["StylesGuideTitle"] = "Styles and Cleaning Guide",
        ["RegexTipsTitle"] = "Advanced Regex Tips",
        ["EnableOrganization"] = "Enable Organization",
        ["BlueprintDesc"] = "Define rules to organize files and folders in-place",
        ["BlueprintHub"] = "Blueprint Center",
        ["NewBlueprintTitle"] = "New Folder Blueprint",
        ["PathToOrganize"] = "Path to Organize",
        ["SidebarBlueprint"] = "Blueprint",
        ["EnableAutoScaffolding"] = "Real-time Monitoring (Auto-Scaffolding)",
        ["AutoScaffoldingTip"] = "Automatically inject the folder structure when a new directory is created or renamed.",
        ["EnableAutoRenaming"] = "Automatic Renaming",
        ["AutoRenamingTip"] = "Automatically rename new files entering this folder based on the template.",
    };

    private Dictionary<string, string> GetEsEsDefaults() => new() {
        ["Dashboard"] = "Panel", ["Jobs"] = "Flujos", ["History"] = "Auditoría", ["Settings"] = "Ajustes", 
        ["Blueprint"] = "Blueprint", ["NewBlueprint"] = "Nuevo Blueprint", ["Flows"] = "Flujos",
        ["Greeting"] = "¡Buenas noches!", ["ActiveAuto"] = "Tienes {0} flujos activos.",
        ["Total"] = "Total", ["Running"] = "Ejecutando", ["Completed"] = "Completado", ["Failed"] = "Fallido",
        ["RecentActivity"] = "Actividad Reciente", ["QuickActions"] = "Acciones Rápidas", ["ErrorAudit"] = "Auditoría",
        ["NewJob"] = "Nuevo Flujo", ["NewAuto"] = "Nuevo Flujo", ["ViewHistory"] = "Ver Historial",
        ["NoErrors"] = "Sin errores registrados.", ["OpenErrorFolder"] = "Abrir Carpeta", ["ClearLogs"] = "Limpiar Logs",
        ["SaveSettings"] = "Guardar Ajustes", ["Appearance"] = "Apariencia", ["SystemTheme"] = "Tema", ["Language"] = "Idioma",
        ["Behavior"] = "Comportamiento", ["ShowNotifications"] = "Notificaciones", ["StartAtStartup"] = "Auto-inicio",
        ["Support"] = "Soporte", ["SupportDesc"] = "¡Apóyanos!", ["BuyCoffee"] = "Invítame a un café",
        ["Add"] = "Añadir", ["Hotfolder"] = "Hotfolder", ["Run"] = "Ejecutar", ["StopAll"] = "Parar Todo", ["Delete"] = "Eliminar",
        ["QueueManagement"] = "GESTIÓN DE COLA", ["OpLog"] = "Log de Operações", ["ManualOp"] = "Operaciones Manuales", ["Automation"] = "Flujos",
        ["HistoryHeader"] = "HISTORIAL DE FLUJOS", ["Update"] = "Actualizar", ["SearchHistory"] = "Buscar...",
        ["NoLogs"] = "No hay logs.",
        ["Copy"] = "Copiar", ["Move"] = "Mover", ["Skip"] = "Omitir", ["Overwrite"] = "Sobrescribir", ["Rename"] = "Renombrar",
        ["None"] = "Ninguno", ["Interval"] = "Intervalo", ["Daily"] = "Diario", ["Weekly"] = "Semanal",
        ["RealTime"] = "Tiempo Real", ["Polling"] = "Sondeo", ["OnSuccess"] = "Al Éxito", ["OnError"] = "Al Error", ["OnBoth"] = "En Ambos",
        ["ControlPanel"] = "Panel de Controle", ["SystemOverview"] = "Visión general del sistema",
        ["Type"] = "Tipo:", ["Task"] = "Tarea:", ["SystemHealth"] = "SALUD DEL SISTEMA", ["TotalVolume"] = "VOLUMEN TOTAL",
        ["ProcessedData"] = "Datos processados", ["TimeSaved"] = "TIEMPO AHORRADO", ["AutomatedWork"] = "Trabajo automatizado",
        ["Files"] = "ARCHIVOS", ["DirectCopy"] = "Flujo Directo", ["WatchFolder"] = "Flujo Activo", ["PauseAll"] = "Pausar Todo",
        ["RecentActivities"] = "ACTIVIDADES RECENTES", ["UpcomingRadar"] = "RADAR DE TAREAS", ["SystemMonitor"] = "MONITOR DEL SISTEMA",
        ["CopySpeed"] = "Velocidad", ["Processor"] = "Procesador", ["Ram"] = "Memoria RAM", ["CloudSync"] = "Sincro Nube",
        ["All"] = "Todos", ["Excellent"] = "Excelente", ["Good"] = "Bueno", ["Attention"] = "Atención", ["Critical"] = "Crítico",
        ["NoData"] = "Sin datos", ["Downloading"] = "Descargando...", ["Synced"] = "Sincronizado", ["GlobalPaused"] = "Procesamiento pausado.", ["GlobalResumed"] = "Procesamiento reanudado.",
        ["AdvancedSettings"] = "Ajustes Avançados", ["SettingsDesc"] = "Control total del sistema",
        ["EnginePerformance"] = "MOTOR Y RENDIMIENTO", ["Parallelism"] = "Paralelismo", ["ParallelismDesc"] = "Archivos simultáneos",
        ["ProcessPriority"] = "Prioridad", ["PriorityDesc"] = "Impacto en el sistema",
        ["GlobalBandwidth"] = "Límite de Banda", ["BandwidthDesc"] = "0 = Ilimitado",
        ["SecurityPrivacy"] = "SEGURIDAD Y PRIVACIDADE", ["AccessPin"] = "PIN de Acesso", ["PinWatermark"] = "Introduce un PIN",
        ["PinDesc"] = "Protege la interfaz", ["LockOnMinimize"] = "Bloquear al minimizar",
        ["EncryptionKey"] = "Clave Maestra", ["EncryptionKeyWatermark"] = "Tu clave global", ["EncryptionDesc"] = "Por defecto para novos jobs",
        ["ExternalNotifications"] = "NOTIFICAÇÕES (WEBHOOK & SMTP)", ["WebhookUrl"] = "URL Webhook",
        ["WebhookUrlWatermark"] = "https://...", ["SmtpServer"] = "Servidor SMTP",
        ["SmtpHostWatermark"] = "smtp.ejemplo.com", ["Port"] = "Puerto", ["DestEmail"] = "Email Destino",
        ["DestEmailWatermark"] = "alertas@email.com", ["EnableSmtp"] = "Activar Email", ["NotifyOnSuccess"] = "Notificar Éxito", ["NotifyOnError"] = "Notificar Error",
        ["AutomationSystem"] = "SISTEMA", ["StartWithWindows"] = "Inicio con Windows", ["StartWithWindowsDesc"] = "Arrancar al encender",
        ["CloseToTray"] = "Cerrar a la Bandeja", ["CloseToTrayDesc"] = "Mantener en segundo plano",
        ["MaintenanceData"] = "MANTENIMIENTO", ["LogRetention"] = "Retención de Logs", ["LogRetentionDesc"] = "Días de historial",
        ["DatabaseSize"] = "Tamaño: {0}", ["ClearNow"] = "Limpiar Ahora", ["OptimizeDatabase"] = "Optimizar BD",
        ["VisualLanguage"] = "VISUAL E IDIOMA", ["InterfaceTheme"] = "Tema", ["SystemLanguage"] = "Idioma",
        ["GlassOpacity"] = "Opacidade Cristal", ["DiscardChanges"] = "Descartar",
        ["ConfigureAutomation"] = "Configurar Flujo", ["AutomationRules"] = "Define reglas y destinos",
        ["General"] = "General", ["Filters"] = "Filtros", ["Schedule"] = "Agenda", ["Security"] = "Segurança", ["Advanced"] = "Avanzado",
        ["JobName"] = "Nombre del Flujo", ["SourcePath"] = "Origen", ["DestPath"] = "Destino", ["WorkMode"] = "Modo",
        ["FileConflicts"] = "Conflictos", ["IncludeExtensions"] = "Extensiones", ["IgnorePatterns"] = "Ignorar",
        ["RegexExpression"] = "Regex", ["WatcherConfigs"] = "WATCHER", ["DetectionMethod"] = "Método",
        ["StabilizationTime"] = "Estabilização", ["ScheduleType"] = "Tipo Agenda", ["RepeatOnDays"] = "Días:",
        ["Sun"] = "D", ["Mon"] = "L", ["Tue"] = "M", ["Wed"] = "M", ["Thu"] = "J", ["Fri"] = "V", ["Sat"] = "S",
        ["ExecutionTime"] = "Hora", ["DataProtection"] = "PROTECCIÓN", ["EncryptionKeyLabel"] = "Clave",
        ["JobWebhooks"] = "WEBHOOKS", ["SimulationSummary"] = "RESUMEN", ["FilesIdentified"] = "Archivos",
        ["DataVolume"] = "Volumen", ["SimulationSuccess"] = "Simulación OK.",
        ["Simulate"] = "Simular", ["NewDirectCopyTitle"] = "Nuevo Flujo Directo", ["NewWatchFolderTitle"] = "Nuevo Flujo Activo",
        ["Save"] = "Guardar", ["Cancel"] = "Cancelar", ["ProcessSubfolders"] = "Subcarpetas", ["SmartSyncLabel"] = "Smart Sync",
        ["VerifyHashLabel"] = "Verificar Hash", ["ClearPreview"] = "Limpiar", ["SaveAutomation"] = "Guardar Flujo",
        ["AuditHistory"] = "Auditoría", ["ForenseTracking"] = "Rastreo de operaciones",
        ["ExportCsv"] = "Exportar CSV", ["OpDetails"] = "DETALLES", ["File"] = "Archivo", ["Destination"] = "Destino",
        ["Size"] = "Tamaño", ["Duration"] = "Duración", ["EngineLogs"] = "Logs Motor", ["SelectEntry"] = "Selecciona una entrada",
        ["SearchWatermark"] = "Buscar...", ["Time"] = "Hora", ["Origin"] = "Origen", ["OpenSourceFolder"] = "Abrir Origen",
        ["OpenDestFolder"] = "Abrir Destino", ["ClearHistory"] = "Limpar Historial", ["Copied"] = "COPIADO",
        ["Moved"] = "MOVIDO", ["Ignored"] = "IGNORADO", ["FailedStatus"] = "FALLIDO", ["Zipped"] = "ZIPADO", ["Cancelled"] = "CANCELADO",
        ["SidebarAutomation"] = "Flujos", ["SidebarAudit"] = "Auditoría", ["AutomationHub"] = "Central de Flujos",
        ["ActiveBadge"] = "{0} Activos", ["QueueReady"] = "Listo", ["AutomationDesc"] = "Gestiona tus flujos",
        ["StopAllTip"] = "Parar Todo", ["Active"] = "Activos", ["Pending"] = "Pendentes", ["Watchers"] = "Watchers",
        ["SearchJobsWatermark"] = "Buscar flujos...", ["SelectedCount"] = "{0} seleccionados", ["RealTimeProcessing"] = "TIEMPO REAL",
        ["ConfiguredTasks"] = "TUS FLUJOS", ["RunTip"] = "Arrancar", ["StopTip"] = "Parar", ["EditTip"] = "Editar", ["DeleteTip"] = "Borrar",
        ["OriginLabel"] = "ORIGEM:", ["DestLabel"] = "DEST:", ["Frequency"] = "FREQ", ["SpeedLabel"] = "VEL", ["LiveTerminal"] = "TERMINAL",
        ["Processing"] = "Ejecutando...", ["Idle"] = "Inactivo", ["Queued"] = "En cola...", ["NewDirectCopy"] = "Nuevo Flujo",
        ["NewWatchFolder"] = "Nueva Watch", ["JobNameWatermark"] = "Ej: Backup", ["Browse"] = "Buscar",
        ["ExtensionsWatermark"] = ".jpg", ["IgnoreWatermark"] = "temp", ["RegexWatermark"] = "^[0-9].*",
        ["OpenApp"] = "Abrir", ["Exit"] = "Salir", ["SuccessBadge"] = "OK", ["IgnoredBadge"] = "IGN", ["ErrorBadge"] = "ERR", ["SmtpEmailHeader"] = "SMTP",
        ["JobStarted"] = "Flujo '{0}' iniciado.", ["RetryMode"] = " [REINTENTO]", ["PreScriptFailed"] = "Script previo falló.",
        ["SourceNotFound"] = "Origen no encontrado: {0}", ["JobError"] = "Error de Flujo", ["JobFailedSourceNotFound"] = "Flujo '{0}' falló: Falta origen.",
        ["StartingFile"] = "Iniciando: {0}", ["SuccessFile"] = "Éxito: {0}", ["ErrorFile"] = "ERROR: {0}",
        ["FilterIgnored"] = "Filtro aplicado.", ["JobFinished"] = "Finalizado: {0}", ["JobCompleted"] = "Flujo Completado",
        ["FilesFailed"] = "{0} fallidos.", ["UserCancelled"] = "Flujo '{0}' cancelado.", ["UserCancelledOp"] = "Cancelado.",
        ["CriticalError"] = "Error Crítico", ["CriticalErrorJob"] = "Error en '{0}': {1}", ["PostScriptFailed"] = "Script post falló.",
        ["IntegrityFailed"] = "Error integridad.", ["ZipCreationFailed"] = "Error ZIP: {0}",
        ["RetentionOldDeleted"] = "Retención: Borrado {0}", ["RetentionExpiredDeleted"] = "Retención: Expirado {0}",
        ["RetentionFailed"] = "Error retención: {0}", ["SmartSyncDetail"] = "SmartSync", ["StartingJobLog"] = "Iniciando Flujo: {0}",
        ["PreviewErrorSourceNotFound"] = "Sin origem: {0}", ["PreviewIgnored"] = "[IGN] {0}",
        ["PreviewIgnoredSmartSync"] = "[SYNC] {0}", ["PreviewIgnoredConflict"] = "[CONF] {0}",
        ["PreviewOverwrite"] = "[SOB] {0}", ["PreviewRename"] = "[REN] {0}", ["PreviewCopy"] = "[COP] {0}", ["PreviewMove"] = "[MOV] {0}",
        ["RamUsageFormat"] = "{0} GB / {1} GB", ["TimeSavedFormat"] = "{0}h {1}m", ["SchedulerLoopError"] = "Error agenda: {0}",
        ["DailyMaintenanceSuccess"] = "Mantenimiento OK.", ["DailyMaintenanceError"] = "Error mantenimiento: {0}",
        ["DailySummaryName"] = "Resumen Diario", ["InXDays"] = "en {0} días", ["InXHours"] = "en {0}h", ["InXMinutes"] = "en {0}min",
        ["SupportTitle"] = "Apoya al Desarrollador", ["SupportPixLabel"] = "Clave Pix (Brasil)", ["SupportCoffeeLabel"] = "Buy Me a Coffee", ["SupportCopyPix"] = "Copiar Clave",
        ["Donate"] = "Donar",
        ["NoWatchers"] = "No se encontraron carpetas monitoreadas.",
        ["NoTransfers"] = "No hay flujos directos configurados.",
        ["NoIncidents"] = "No hay incidentes registrados. ¡Todo funciona bien!",
        ["NoSystemLogs"] = "No hay eventos de sistema registrados.",
        ["NoFileBlueprints"] = "No hay modelos de organización de archivos.",
        ["NoFolderBlueprints"] = "No hay modelos de estructura de carpetas.",
        
        // Organization (Blueprint)
        ["Organization"] = "Blueprint",
        ["Scaffolding"] = "Estructura",
        ["ScaffoldingDesc"] = "Crear subcarpetas automáticamente",
        ["Renaming"] = "Renombrado",
        ["RenamingDesc"] = "Estandarizar nombres de archivos",
        ["FolderBlueprint"] = "Planta de Carpetas",
        ["AddFolder"] = "Añadir Carpeta",
        ["RenameTemplateLabel"] = "Plantilla de Nombres",
        ["TokensAvailable"] = "Tokens: {Date}, {JobName}, {FileName}, {Ext}, {Parent}",
        ["EnableOrganization"] = "Activar Blueprint",
        ["BlueprintDesc"] = "Reglas para organizar carpetas in-situ",
        ["BlueprintHub"] = "Centro de Blueprint",
        ["NewBlueprintTitle"] = "Nuevo Blueprint",
        ["PathToOrganize"] = "Ruta a Organizar",
        ["SidebarBlueprint"] = "Blueprint",
        ["EnableAutoScaffolding"] = "Monitorización en Tiempo Real (Auto-Scaffolding)",
        ["AutoScaffoldingTip"] = "Inyecta automáticamente la estructura de carpetas cuando se crea o renombra un nuevo directorio.",
        ["EnableAutoRenaming"] = "Renombrado Automático",
        ["AutoRenamingTip"] = "Renombra automáticamente los nuevos archivos que entren en esta carpeta según la plantilla.",
    };

    private Dictionary<string, string> GetJaJpDefaults() => new() {
        ["Dashboard"] = "ダッシュボード", ["Jobs"] = "フロー", ["History"] = "履歴", ["Settings"] = "設定", 
        ["Blueprint"] = "ブループリント", ["NewBlueprint"] = "新規作成", ["Flows"] = "フロー",
        ["Greeting"] = "こんにちは！", ["ActiveAuto"] = "{0} 個のフローが有効です。",
        ["Total"] = "合計", ["Running"] = "実行中", ["Completed"] = "完了", ["Failed"] = "失敗",
        ["RecentActivity"] = "最近の活動", ["QuickActions"] = "アクション", ["ErrorAudit"] = "監査",
        ["NewJob"] = "新規フロー", ["NewAuto"] = "新規フロー", ["ViewHistory"] = "履歴表示",
        ["NoErrors"] = "エラーなし", ["OpenErrorFolder"] = "フォルダを開く", ["ClearLogs"] = "ログ削除",
        ["SaveSettings"] = "設定保存", ["Appearance"] = "外観", ["SystemTheme"] = "テーマ", ["Language"] = "言語",
        ["Behavior"] = "動作", ["ShowNotifications"] = "通知を表示", ["StartAtStartup"] = "自動起動",
        ["Support"] = "サポート", ["SupportDesc"] = "開発者を支援する", ["BuyCoffee"] = "コーヒーを買う",
        ["Add"] = "追加", ["Hotfolder"] = "ホットフォルダ", ["Run"] = "開始", ["StopAll"] = "全停止", ["Delete"] = "削除",
        ["QueueManagement"] = "キュー管理", ["OpLog"] = "操作ログ", ["ManualOp"] = "手動操作", ["Automation"] = "フロー",
        ["HistoryHeader"] = "フロー履歴", ["Update"] = "更新", ["SearchHistory"] = "検索...",
        ["NoLogs"] = "ログなし",
        ["Copy"] = "コピー", ["Move"] = "移動", ["Skip"] = "スキップ", ["Overwrite"] = "上書き", ["Rename"] = "名前変更",
        ["None"] = "なし", ["Interval"] = "間隔", ["Daily"] = "毎日", ["Weekly"] = "毎週",
        ["RealTime"] = "リアルタイム", ["Polling"] = "ポーリング", ["OnSuccess"] = "成功時", ["OnError"] = "エラー時", ["OnBoth"] = "両方",
        ["ControlPanel"] = "コントロールパネル", ["SystemOverview"] = "システム概要",
        ["Type"] = "タイプ:", ["Task"] = "フロー:", ["SystemHealth"] = "システム状態", ["TotalVolume"] = "総ボリューム",
        ["ProcessedData"] = "処理済みデータ", ["TimeSaved"] = "節約された時間", ["AutomatedWork"] = "自動化された作業",
        ["Files"] = "ファイル", ["DirectCopy"] = "直接フロー", ["WatchFolder"] = "アクティブフロー", ["PauseAll"] = "全一時停止",
        ["RecentActivities"] = "最近の活動", ["UpcomingRadar"] = "スケジュール予定", ["SystemMonitor"] = "システムモニター",
        ["CopySpeed"] = "転送速度", ["Processor"] = "CPU使用率", ["Ram"] = "メモリ", ["CloudSync"] = "クラウド同期",
        ["All"] = "すべて", ["Excellent"] = "良好", ["Good"] = "普通", ["Attention"] = "注意", ["Critical"] = "危険",
        ["NoData"] = "データなし", ["Downloading"] = "ダウンロード中...", ["Synced"] = "同期済み", ["GlobalPaused"] = "一時停止中", ["GlobalResumed"] = "再開済み",
        ["AdvancedSettings"] = "詳細設定", ["SettingsDesc"] = "パフォーマンスと統合の設定",
        ["EnginePerformance"] = "エンジンとパフォーマンス", ["Parallelism"] = "並列処理", ["ParallelismDesc"] = "同時処理数",
        ["ProcessPriority"] = "優先度", ["PriorityDesc"] = "システムへの影響",
        ["GlobalBandwidth"] = "帯域幅制限", ["BandwidthDesc"] = "0 = 無制限",
        ["SecurityPrivacy"] = "セキュリティ", ["AccessPin"] = "アクセスPIN", ["PinWatermark"] = "PINを入力",
        ["PinDesc"] = "パスワード保護", ["LockOnMinimize"] = "最小化時にロック",
        ["EncryptionKey"] = "暗号化キー", ["EncryptionKeyWatermark"] = "グローバルキー", ["EncryptionDesc"] = "新規ジョブのデフォルト",
        ["ExternalNotifications"] = "外部通知", ["WebhookUrl"] = "Webhook URL",
        ["WebhookUrlWatermark"] = "https://...", ["SmtpServer"] = "SMTPサーバー",
        ["SmtpHostWatermark"] = "smtp.gmail.com", ["Port"] = "ポート", ["DestEmail"] = "宛先メール",
        ["DestEmailWatermark"] = "alerts@email.com", ["EnableSmtp"] = "メール有効化", ["NotifyOnSuccess"] = "成功を通知", ["NotifyOnError"] = "エラーを通知",
        ["AutomationSystem"] = "システム設定", ["StartWithWindows"] = "Windows起動時に開始", ["StartWithWindowsDesc"] = "自動実行",
        ["CloseToTray"] = "トレイに閉じる", ["CloseToTrayDesc"] = "バックグラウンド実行",
        ["MaintenanceData"] = "メンテナンス", ["LogRetention"] = "ログ保持期間", ["LogRetentionDesc"] = "保存日数",
        ["DatabaseSize"] = "サイズ: {0}", ["ClearNow"] = "今すぐ削除", ["OptimizeDatabase"] = "最適化",
        ["VisualLanguage"] = "表示と言語", ["InterfaceTheme"] = "テーマ", ["SystemLanguage"] = "システム言語",
        ["GlassOpacity"] = "不透明度", ["DiscardChanges"] = "破棄",
        ["ConfigureAutomation"] = "フロー設定", ["AutomationRules"] = "ルールと宛先の設定",
        ["General"] = "一般", ["Filters"] = "フィルタ", ["Schedule"] = "スケジュール", ["Security"] = "安全", ["Advanced"] = "詳細",
        ["JobName"] = "フロー名", ["SourcePath"] = "元のパス", ["DestPath"] = "保存先パス", ["WorkMode"] = "動作モード",
        ["FileConflicts"] = "競合解決", ["IncludeExtensions"] = "拡張子指定", ["IgnorePatterns"] = "除外パターン",
        ["RegexExpression"] = "正規表現", ["WatcherConfigs"] = "監視設定", ["DetectionMethod"] = "検出方法",
        ["StabilizationTime"] = "安定化時間", ["ScheduleType"] = "スケジュール形式", ["RepeatOnDays"] = "実行日:",
        ["Sun"] = "日", ["Mon"] = "月", ["Tue"] = "火", ["Wed"] = "水", ["Thu"] = "木", ["Fri"] = "金", ["Sat"] = "土",
        ["ExecutionTime"] = "実行時間", ["DataProtection"] = "データ保護", ["EncryptionKeyLabel"] = "暗号化キー",
        ["JobWebhooks"] = "Webhook設定", ["SimulationSummary"] = "シミュレーション結果", ["FilesIdentified"] = "特定ファイル",
        ["DataVolume"] = "データ量", ["SimulationSuccess"] = "シミュレーション成功",
        ["Simulate"] = "プレビュー", ["NewDirectCopyTitle"] = "新規直接フロー", ["NewWatchFolderTitle"] = "新規アクティブフロー",
        ["Save"] = "保存", ["Cancel"] = "キャンセル", ["ProcessSubfolders"] = "サブフォルダを含む", ["SmartSyncLabel"] = "スマート同期",
        ["VerifyHashLabel"] = "整合性確認", ["ClearPreview"] = "クリア", ["SaveAutomation"] = "フロー保存",
        ["AuditHistory"] = "監査と履歴", ["ForenseTracking"] = "全操作の追跡",
        ["ExportCsv"] = "CSV出力", ["OpDetails"] = "詳細情報", ["File"] = "ファイル", ["Destination"] = "宛先",
        ["Size"] = "サイズ", ["Duration"] = "所要時間", ["EngineLogs"] = "エンジンログ", ["SelectEntry"] = "項目を選択",
        ["SearchWatermark"] = "検索中...", ["Time"] = "時間", ["Origin"] = "元", ["OpenSourceFolder"] = "元フォルダを開く",
        ["OpenDestFolder"] = "先フォルダを開く", ["ClearHistory"] = "履歴をクリア", ["Copied"] = "コピー済み",
        ["Moved"] = "移動済み", ["Ignored"] = "無視", ["FailedStatus"] = "失敗", ["Zipped"] = "圧縮済み", ["Cancelled"] = "キャンセル",
        ["SidebarAutomation"] = "フロー", ["SidebarAudit"] = "監査", ["AutomationHub"] = "フローセンター",
        ["ActiveBadge"] = "{0} 実行中", ["QueueReady"] = "準備完了", ["AutomationDesc"] = "データフローの管理",
        ["StopAllTip"] = "すべて停止", ["Active"] = "有効", ["Pending"] = "保留中", ["Watchers"] = "監視中",
        ["SearchJobsWatermark"] = "フローを検索...", ["SelectedCount"] = "{0}件選択", ["RealTimeProcessing"] = "リアルタイム処理",
        ["ConfiguredTasks"] = "マイフロー", ["RunTip"] = "実行", ["StopTip"] = "停止", ["EditTip"] = "編集", ["DeleteTip"] = "削除",
        ["OriginLabel"] = "元:", ["DestLabel"] = "先:", ["Frequency"] = "頻度", ["SpeedLabel"] = "速度", ["LiveTerminal"] = "ターミナル",
        ["Processing"] = "処理中...", ["Idle"] = "待機中", ["Queued"] = "待機中...", ["NewDirectCopy"] = "新規フロー",
        ["NewWatchFolder"] = "新規監視", ["JobNameWatermark"] = "例: バックアップ", ["Browse"] = "参照",
        ["ExtensionsWatermark"] = ".jpg, .pdf", ["IgnoreWatermark"] = "temp", ["RegexWatermark"] = "^[0-9].*",
        ["OpenApp"] = "アプリを開く", ["Exit"] = "終了", ["SuccessBadge"] = "OK", ["IgnoredBadge"] = "無視", ["ErrorBadge"] = "エラー", ["SmtpEmailHeader"] = "SMTPメール",
        ["JobStarted"] = "フロー '{0}' を開始しました。", ["RetryMode"] = " [再試行]", ["PreScriptFailed"] = "前処理失敗。",
        ["SourceNotFound"] = "元フォルダが見つかりません: {0}", ["JobError"] = "フローエラー", ["JobFailedSourceNotFound"] = "フロー '{0}' 失敗: 元なし",
        ["StartingFile"] = "開始: {0}", ["SuccessFile"] = "成功: {0}", ["ErrorFile"] = "エラー: {0}",
        ["FilterIgnored"] = "フィルタで除外されました。", ["JobFinished"] = "終了: {0}", ["JobCompleted"] = "フロー完了",
        ["FilesFailed"] = "{0}個のファイルが失敗しました。", ["UserCancelled"] = "ユーザーにより中止。", ["UserCancelledOp"] = "中止済み。",
        ["CriticalError"] = "致命的なエラー", ["CriticalErrorJob"] = "エラー '{0}': {1}", ["PostScriptFailed"] = "後処理失敗。",
        ["IntegrityFailed"] = "整合性確認失敗。", ["ZipCreationFailed"] = "ZIP作成失敗: {0}",
        ["RetentionOldDeleted"] = "保持期限: 削除 {0}", ["RetentionExpiredDeleted"] = "保持期限: 期限切れ {0}",
        ["RetentionFailed"] = "保持期限適用失敗: {0}", ["SmartSyncDetail"] = "スマート同期", ["StartingJobLog"] = "フロー開始: {0}",
        ["PreviewErrorSourceNotFound"] = "元なし: {0}", ["PreviewIgnored"] = "[無視] {0}",
        ["PreviewIgnoredSmartSync"] = "[同期] {0}", ["PreviewIgnoredConflict"] = "[競合] {0}",
        ["PreviewOverwrite"] = "[上書き] {0}", ["PreviewRename"] = "[名前変更] {0}", ["PreviewCopy"] = "[コピー] {0}", ["PreviewMove"] = "[移動] {0}",
        ["RamUsageFormat"] = "{0} GB / {1} GB", ["TimeSavedFormat"] = "{0}時間 {1}分", ["SchedulerLoopError"] = "スケジュールエラー: {0}",
        ["DailyMaintenanceSuccess"] = "メンテナンス完了。", ["DailyMaintenanceError"] = "メンテナンスエラー: {0}",
        ["DailySummaryName"] = "デイリーサマリー", ["InXDays"] = "{0}日後", ["InXHours"] = "{0}時間後", ["InXMinutes"] = "{0}分後",
        ["SupportTitle"] = "開発者を支援", ["SupportPixLabel"] = "Pixキー (ブラジル)", ["SupportCoffeeLabel"] = "コーヒーを買う", ["SupportCopyPix"] = "キーをコピー",
        ["Donate"] = "寄付",
        ["NoWatchers"] = "監視対象のフォルダが見つかりません。",
        ["NoTransfers"] = "直接フローが設定されていません。",
        ["NoIncidents"] = "インシデントは記録されていません。すべて正常です！",
        ["NoSystemLogs"] = "システムイベントは記録されていません。",
        ["NoFileBlueprints"] = "ファイル整理モデルがありません。",
        ["NoFolderBlueprints"] = "フォルダ構造モデルがありません。",
        
        // Organization (Blueprint)
        ["Organization"] = "ブループリント",
        ["Scaffolding"] = "構造作成",
        ["ScaffoldingDesc"] = "新規フォルダを検知して自動作成",
        ["Renaming"] = "リネーム",
        ["RenamingDesc"] = "ファイル名を標準化",
        ["FolderBlueprint"] = "フォルダ設計図",
        ["AddFolder"] = "フォルダ追加",
        ["RenameTemplateLabel"] = "テンプレート",
        ["TokensAvailable"] = "利用可能: {Date}, {JobName}, {FileName}, {Ext}, {Parent}",
        ["EnableOrganization"] = "有効化",
        ["BlueprintDesc"] = "フォルダ内の自動整理ルール",
        ["BlueprintHub"] = "ブループリントセンター",
        ["NewBlueprintTitle"] = "新規ブループリント",
        ["PathToOrganize"] = "整理対象パス",
        ["SidebarBlueprint"] = "整理",
        ["EnableAutoScaffolding"] = "リアルタイム監視 (構造自動作成)",
        ["AutoScaffoldingTip"] = "新しいフォルダが作成または名前変更されたとき、自動的に構造を注入します。",
        ["EnableAutoRenaming"] = "自動リネーム",
        ["AutoRenamingTip"] = "このフォルダに入る新しいファイルをテンプレートに従って自動的にリネームします。",
    };

    private Dictionary<string, string> GetRuRuDefaults() => new() {
        ["Dashboard"] = "Панель", ["Jobs"] = "Потоки", ["History"] = "Аудит", ["Settings"] = "Настройки", 
        ["Blueprint"] = "Шаблон", ["NewBlueprint"] = "Новый шаблон", ["Flows"] = "Потоки",
        ["Greeting"] = "Добрый вечер!", ["ActiveAuto"] = "Активных потоков: {0}.",
        ["Total"] = "Всего", ["Running"] = "Запущено", ["Completed"] = "Готово", ["Failed"] = "Ошибка",
        ["RecentActivity"] = "Активность", ["QuickActions"] = "Действия", ["ErrorAudit"] = "Аудит",
        ["NewJob"] = "Новый поток", ["NewAuto"] = "Новый поток", ["ViewHistory"] = "История",
        ["NoErrors"] = "Ошибок нет.", ["OpenErrorFolder"] = "Открыть папку", ["ClearLogs"] = "Очистить",
        ["SaveSettings"] = "Сохранить", ["Appearance"] = "Внешний вид", ["SystemTheme"] = "Тема", ["Language"] = "Язык",
        ["Behavior"] = "Поведение", ["ShowNotifications"] = "Уведомления", ["StartAtStartup"] = "Автозагрузка",
        ["Support"] = "Поддержка", ["SupportDesc"] = "Поддержите нас!", ["BuyCoffee"] = "Купить кофе",
        ["Add"] = "Добавить", ["Hotfolder"] = "Хотфолдер", ["Run"] = "Пуск", ["StopAll"] = "Стоп", ["Delete"] = "Удалить",
        ["QueueManagement"] = "УПРАВЛЕНИЕ ОЧЕРЕДЬЮ", ["OpLog"] = "Лог операций", ["ManualOp"] = "Вручную", ["Automation"] = "Потоки",
        ["HistoryHeader"] = "ИСТОРИЯ ПОТОКОВ", ["Update"] = "Обновить", ["SearchHistory"] = "Поиск...",
        ["NoLogs"] = "Логов нет.",
        ["Copy"] = "Копировать", ["Move"] = "Переместить", ["Skip"] = "Пропустить", ["Overwrite"] = "Заменить", ["Rename"] = "Переименовать",
        ["None"] = "Нет", ["Interval"] = "Интервал", ["Daily"] = "Ежедневно", ["Weekly"] = "Еженедельно",
        ["RealTime"] = "В реальном времени", ["Polling"] = "Опрос", ["OnSuccess"] = "При успехе", ["OnError"] = "При ошибке", ["OnBoth"] = "Всегда",
        ["ControlPanel"] = "Панель управления", ["SystemOverview"] = "Обзор системы",
        ["Type"] = "Тип:", ["Task"] = "Поток:", ["SystemHealth"] = "СОСТОЯНИЕ СИСТЕМЫ", ["TotalVolume"] = "ОБЪЕМ",
        ["ProcessedData"] = "Обработано", ["TimeSaved"] = "ВРЕМЯ СЭКОНОМЛЕНО", ["AutomatedWork"] = "Автоматизировано",
        ["Files"] = "ФАЙЛЫ", ["DirectCopy"] = "Прямой поток", ["WatchFolder"] = "Активный поток", ["PauseAll"] = "Пауза",
        ["RecentActivities"] = "АКТИВНОСТЬ", ["UpcomingRadar"] = "РАСПИСАНИЕ", ["SystemMonitor"] = "МОНИТОРИНГ",
        ["CopySpeed"] = "Скорость", ["Processor"] = "Процессор", ["Ram"] = "Память RAM", ["CloudSync"] = "Облако",
        ["All"] = "Все", ["Excellent"] = "Отлично", ["Good"] = "Хорошо", ["Attention"] = "Внимание", ["Critical"] = "Критично",
        ["NoData"] = "Нет данных", ["Downloading"] = "Загрузка...", ["Synced"] = "Синхронизировано", ["GlobalPaused"] = "Пауза.", ["GlobalResumed"] = "Возобновлено.",
        ["AdvancedSettings"] = "Настройки", ["SettingsDesc"] = "Производительность и вид",
        ["EnginePerformance"] = "ДВИЖОК", ["Parallelism"] = "Потоки", ["ParallelismDesc"] = "Одновременные файлы",
        ["ProcessPriority"] = "Приоритет", ["PriorityDesc"] = "Влияние на Windows",
        ["GlobalBandwidth"] = "Лимит скорости", ["BandwidthDesc"] = "0 = Без лимита",
        ["SecurityPrivacy"] = "БЕЗОПАСНОСТЬ", ["AccessPin"] = "PIN-код", ["PinWatermark"] = "Введите PIN",
        ["PinDesc"] = "Защита паролем", ["LockOnMinimize"] = "Блок. при сворачивании",
        ["EncryptionKey"] = "Ключ шифрования", ["EncryptionKeyWatermark"] = "Глобальный ключ", ["EncryptionDesc"] = "Для новых задач",
        ["ExternalNotifications"] = "УВЕДОМЛЕНИЯ", ["WebhookUrl"] = "Webhook URL",
        ["WebhookUrlWatermark"] = "https://...", ["SmtpServer"] = "SMTP сервер",
        ["SmtpHostWatermark"] = "smtp.yandex.ru", ["Port"] = "Порт", ["DestEmail"] = "Email получателя",
        ["DestEmailWatermark"] = "admin@mail.ru", ["EnableSmtp"] = "Включить Email", ["NotifyOnSuccess"] = "При успехе", ["NotifyOnError"] = "При ошибке",
        ["AutomationSystem"] = "СИСТЕМА", ["StartWithWindows"] = "Автозапуск", ["StartWithWindowsDesc"] = "При входе в Windows",
        ["CloseToTray"] = "В трей", ["CloseToTrayDesc"] = "Работа в фоне",
        ["MaintenanceData"] = "ДАННЫЕ", ["LogRetention"] = "Хранение логов", ["LogRetentionDesc"] = "Дней в истории",
        ["DatabaseSize"] = "Размер: {0}", ["ClearNow"] = "Очистить сейчас", ["OptimizeDatabase"] = "Оптимизировать",
        ["VisualLanguage"] = "ВИД И ЯЗЫК", ["InterfaceTheme"] = "Тема", ["SystemLanguage"] = "Язык",
        ["GlassOpacity"] = "Прозрачность", ["DiscardChanges"] = "Сбросить",
        ["ConfigureAutomation"] = "Настройка потока", ["AutomationRules"] = "Правила и пути",
        ["General"] = "Общие", ["Filters"] = "Фильтры", ["Schedule"] = "График", ["Security"] = "Защита", ["Advanced"] = "Доп.",
        ["JobName"] = "Название потока", ["SourcePath"] = "Источник", ["DestPath"] = "Назначение", ["WorkMode"] = "Режим",
        ["FileConflicts"] = "Конфликты", ["IncludeExtensions"] = "Расширения", ["IgnorePatterns"] = "Игнорировать",
        ["RegexExpression"] = "Regex", ["WatcherConfigs"] = "WATCHER", ["DetectionMethod"] = "Метод",
        ["StabilizationTime"] = "Стабилизация", ["ScheduleType"] = "Тип графика", ["RepeatOnDays"] = "Дни:",
        ["Sun"] = "В", ["Mon"] = "П", ["Tue"] = "В", ["Wed"] = "С", ["Thu"] = "Ч", ["Fri"] = "П", ["Sat"] = "С",
        ["ExecutionTime"] = "Время", ["DataProtection"] = "ЗАЩИТА ДАННЫХ", ["EncryptionKeyLabel"] = "Ключ",
        ["JobWebhooks"] = "WEBHOOKS", ["SimulationSummary"] = "ПРЕВЬЮ", ["FilesIdentified"] = "Файлов",
        ["DataVolume"] = "Объем", ["SimulationSuccess"] = "Успешно.",
        ["Simulate"] = "Тест", ["NewDirectCopyTitle"] = "Новый прямой поток", ["NewWatchFolderTitle"] = "Новый активный поток",
        ["Save"] = "ОК", ["Cancel"] = "Отмена", ["ProcessSubfolders"] = "Включая подпапки", ["SmartSyncLabel"] = "Smart Sync",
        ["VerifyHashLabel"] = "Проверка Hash", ["ClearPreview"] = "Очистить", ["SaveAutomation"] = "Сохранить поток",
        ["AuditHistory"] = "Аудит", ["ForenseTracking"] = "История всех операций",
        ["ExportCsv"] = "В CSV", ["OpDetails"] = "ДЕТАЛИ", ["File"] = "Файл", ["Destination"] = "Куда",
        ["Size"] = "Размер", ["Duration"] = "Время", ["EngineLogs"] = "Лог движка", ["SelectEntry"] = "Выберите запись",
        ["SearchWatermark"] = "Поиск...", ["Time"] = "Время", ["Origin"] = "Откуда", ["OpenSourceFolder"] = "Открыть источник",
        ["OpenDestFolder"] = "Открыть цель", ["ClearHistory"] = "Очистить историю", ["Copied"] = "ОК: КОПИЯ",
        ["Moved"] = "ОК: ПЕРЕНОС", ["Ignored"] = "ПРОПУЩЕНО", ["FailedStatus"] = "ОШИБКА", ["Zipped"] = "В АРХИВЕ", ["Cancelled"] = "ОТМЕНЕНО",
        ["SidebarAutomation"] = "Потоки", ["SidebarAudit"] = "Аудит", ["AutomationHub"] = "Центр потоков",
        ["ActiveBadge"] = "{0} Активно", ["QueueReady"] = "Готов", ["AutomationDesc"] = "Управление потоками",
        ["StopAllTip"] = "Стоп все", ["Active"] = "Активны", ["Pending"] = "Ожидают", ["Watchers"] = "Watchers",
        ["SearchJobsWatermark"] = "Поиск потоков...", ["SelectedCount"] = "{0} выбрано", ["RealTimeProcessing"] = "LIVE РЕЖИМ",
        ["ConfiguredTasks"] = "МОИ ПОТОКИ", ["RunTip"] = "Пуск", ["StopTip"] = "Стоп", ["EditTip"] = "Правка", ["DeleteTip"] = "Удалить",
        ["OriginLabel"] = "ОТКУДА:", ["DestLabel"] = "КУДА:", ["Frequency"] = "ГРАФИК", ["SpeedLabel"] = "СКОРОСТЬ", ["LiveTerminal"] = "ТЕРМИНАЛ",
        ["Processing"] = "В работе...", ["Idle"] = "Спит", ["Queued"] = "В очереди...", ["NewDirectCopy"] = "Новый поток",
        ["NewWatchFolder"] = "Watch", ["JobNameWatermark"] = "Напр. Бэкап", ["Browse"] = "Обзор",
        ["ExtensionsWatermark"] = ".jpg, .zip", ["IgnoreWatermark"] = "temp", ["RegexWatermark"] = "^[0-9].*",
        ["OpenApp"] = "Открыть", ["Exit"] = "Выход", ["SuccessBadge"] = "OK", ["IgnoredBadge"] = "IGN", ["ErrorBadge"] = "ERR", ["SmtpEmailHeader"] = "SMTP / Email",
        ["JobStarted"] = "Поток '{0}' запущен.", ["RetryMode"] = " [RETRY]", ["PreScriptFailed"] = "Pre-script ошибка.",
        ["SourceNotFound"] = "Не найден путь: {0}", ["JobError"] = "Ошибка потока", ["JobFailedSourceNotFound"] = "Поток '{0}' ошибка: Путь отсутствует.",
        ["StartingFile"] = "Старт: {0}", ["SuccessFile"] = "ОК: {0}", ["ErrorFile"] = "ОШИБКА: {0}",
        ["FilterIgnored"] = "Фильтр.", ["JobFinished"] = "Готово: {0}", ["JobCompleted"] = "Поток Готов",
        ["FilesFailed"] = "Ошибок: {0}.", ["UserCancelled"] = "Отмена пользователем.", ["UserCancelledOp"] = "Отменено.",
        ["CriticalError"] = "Крит. ошибка", ["CriticalErrorJob"] = "Ошибка в '{0}': {1}", ["PostScriptFailed"] = "Post-script ошибка.",
        ["IntegrityFailed"] = "Ошибка целостности.", ["ZipCreationFailed"] = "Ошибка ZIP: {0}",
        ["RetentionOldDeleted"] = "Удалено по сроку { Russian }", ["RetentionExpiredDeleted"] = "Удалено: истек срок {0}",
        ["RetentionFailed"] = "Ошибка очистки: {0}", ["SmartSyncDetail"] = "SmartSync", ["StartingJobLog"] = "Старт потока: {0}",
        ["PreviewErrorSourceNotFound"] = "Нет пути: {0}", ["PreviewIgnored"] = "[SKIP] {0}",
        ["PreviewIgnoredSmartSync"] = "[SYNC] {0}", ["PreviewIgnoredConflict"] = "[CONF] {0}",
        ["PreviewOverwrite"] = "[OVER] {0}", ["PreviewRename"] = "[REN] {0}", ["PreviewCopy"] = "[COPY] {0}", ["PreviewMove"] = "[MOVE] {0}",
        ["RamUsageFormat"] = "{0} ГБ / {1} GB", ["TimeSavedFormat"] = "{0}ч {1}м", ["SchedulerLoopError"] = "Ошибка планировщика: {0}",
        ["DailyMaintenanceSuccess"] = "Обслуживание завершено.", ["DailyMaintenanceError"] = "Ошибка обслуживания: {0}",
        ["DailySummaryName"] = "Отчет за день", ["InXDays"] = "через {0} д.", ["InXHours"] = "через {0} ч.", ["InXMinutes"] = "через {0} мин.",
        ["SupportTitle"] = "Поддержка разработчика", ["SupportPixLabel"] = "Pix ключ (Бразилия)", ["SupportCoffeeLabel"] = "Купить кофе", ["SupportCopyPix"] = "Копировать",
        ["Donate"] = "Донат",
        ["NoWatchers"] = "Наблюдаемые папки не найдены.",
        ["NoTransfers"] = "Прямые потоки не настроены.",
        ["NoIncidents"] = "Инцидентов нет. Все работает отлично!",
        ["NoSystemLogs"] = "Системные события не зарегистрированы.",
        ["NoFileBlueprints"] = "Нет шаблонов организации файлов.",
        ["NoFolderBlueprints"] = "Нет шаблонов структуры папок.",
        
        // Organization (Blueprint)
        ["Organization"] = "Шаблон",
        ["Scaffolding"] = "Структура папок",
        ["ScaffoldingDesc"] = "Автоматическое создание подпапок",
        ["Renaming"] = "Переименование",
        ["RenamingDesc"] = "Стандартизация имен",
        ["FolderBlueprint"] = "Шаблон папок",
        ["AddFolder"] = "Добавить папку",
        ["RenameTemplateLabel"] = "Шаблон имен",
        ["TokensAvailable"] = "Токены: {Date}, {JobName}, {FileName}, {Ext}, {Parent}",
        ["EnableOrganization"] = "Включить Blueprint",
        ["BlueprintDesc"] = "Правила организации папок на месте",
        ["BlueprintHub"] = "Центр шаблонов",
        ["NewBlueprintTitle"] = "Новый Blueprint",
        ["PathToOrganize"] = "Путь организации",
        ["SidebarBlueprint"] = "Шаблон",
        ["EnableAutoScaffolding"] = "Мониторинг в реальном времени (Auto-Scaffolding)",
        ["AutoScaffoldingTip"] = "Автоматически создавать структуру папок при создании или переименовании новой папки.",
        ["EnableAutoRenaming"] = "Автоматическое переименование",
        ["AutoRenamingTip"] = "Автоматически переименовывать новые файлы в этой папке по шаблону.",
    };

    private Dictionary<string, string> GetPtBrDefaults() => new() {
        ["Dashboard"] = "Painel", ["Jobs"] = "Fluxos", ["History"] = "Auditoria", ["Settings"] = "Configurações", 
        ["Blueprint"] = "Blueprint", ["NewBlueprint"] = "Novo Blueprint", ["Flows"] = "Fluxos",
        ["Greeting"] = "Boa noite!", ["ActiveAuto"] = "Você tem {0} fluxos ativos.",
        ["Total"] = "Total", ["Running"] = "Rodando", ["Completed"] = "Concluído", ["Failed"] = "Falhou",
        ["RecentActivity"] = "Atividade Recente", ["QuickActions"] = "Ações Rápidas", ["ErrorAudit"] = "Auditoria de Erros",
        ["NewJob"] = "Novo Fluxo", ["NewAuto"] = "Novo Fluxo", ["ViewHistory"] = "Ver Histórico",
        ["NoErrors"] = "Nenhum erro registrado no sistema.", ["OpenErrorFolder"] = "Abrir Pasta de Erros", ["ClearLogs"] = "Limpar Logs",
        ["SaveSettings"] = "Salvar Configurações", ["Appearance"] = "Aparência e Localização", ["SystemTheme"] = "Tema do Aplicativo", ["Language"] = "Idioma (Cultura)",
        ["Behavior"] = "Comportamento do Sistema", ["ShowNotifications"] = "Exibir notificações na área de trabalho (Toasts)", ["StartAtStartup"] = "Iniciar AutoFlow automaticamente com o sistema (Background)",
        ["Support"] = "Suporte e Doação", ["SupportDesc"] = "Se o AutoFlow tem sido útil para você, considere apoiar o desenvolvedor!", ["BuyCoffee"] = "Apoie o desenvolvedor",
        ["Add"] = "Adicionar", ["Hotfolder"] = "Hotfolder", ["Run"] = "Rodar", ["StopAll"] = "Parar Tudo", ["Delete"] = "Excluir",
        ["QueueManagement"] = "GERENCIAR FILA DE OPERAÇÕES", ["OpLog"] = "Log de Operações", ["ManualOp"] = "Operações Manuais", ["Automation"] = "Fluxos",
        ["HistoryHeader"] = "HISTÓRICO DE FLUXOS", ["Update"] = "Atualizar", ["SearchHistory"] = "Pesquisar arquivo ou destino...",
        ["NoLogs"] = "Nenhum log encontrado.",
        ["Copy"] = "Copiar", ["Move"] = "Mover", ["Skip"] = "Pular", ["Overwrite"] = "Sobrescrever", ["Rename"] = "Renomear",
        ["None"] = "Nenhum", ["Interval"] = "Intervalo", ["Daily"] = "Diário", ["Weekly"] = "Semanal",
        ["RealTime"] = "Tempo Real", ["Polling"] = "Varredura (Polling)", ["OnSuccess"] = "No Sucesso", ["OnError"] = "No Erro", ["OnBoth"] = "Em Ambos",
        ["ControlPanel"] = "Painel de Controle", ["SystemOverview"] = "Visão geral do sistema e métricas de desempenho",
        ["Type"] = "Tipo:", ["Task"] = "Fluxo:", ["SystemHealth"] = "SAÚDE DO SISTEMA", ["TotalVolume"] = "VOLUME TOTAL",
        ["ProcessedData"] = "Dados processados", ["TimeSaved"] = "TEMPO ECONOMIZADO", ["AutomatedWork"] = "Trabalho automatizado",
        ["Files"] = "ARQUIVOS", ["DirectCopy"] = "Fluxo Direto", ["WatchFolder"] = "Fluxo Ativo", ["PauseAll"] = "Pausar Tudo",
        ["RecentActivities"] = "ATIVIDADES RECENTES", ["UpcomingRadar"] = "RADAR DE AGENDAMENTOS", ["SystemMonitor"] = "MONITOR DO SISTEMA",
        ["CopySpeed"] = "Velocidade de Fluxo", ["Processor"] = "Processador (CPU)", ["Ram"] = "Memória RAM", ["CloudSync"] = "Sincronização Nuvem",
        ["All"] = "Todos", ["Excellent"] = "Excelente", ["Good"] = "Bom", ["Attention"] = "Atenção", ["Critical"] = "Crítico",
        ["NoData"] = "Sem dados", ["Downloading"] = "Baixando...", ["Synced"] = "Sincronizado", ["GlobalPaused"] = "Processamento global pausado.", ["GlobalResumed"] = "Processamento global retomado.",
        ["AdvancedSettings"] = "Configurações Avançadas", ["SettingsDesc"] = "Controle total sobre performance, integração e visual",
        ["EnginePerformance"] = "MOTOR E PERFORMANCE", ["Parallelism"] = "Paralelismo (Threads)", ["ParallelismDesc"] = "Número de arquivos processados simultaneamente",
        ["ProcessPriority"] = "Prioridade do Processo", ["PriorityDesc"] = "Impacto do software no desempenho do Windows",
        ["GlobalBandwidth"] = "Limite de Banda Global", ["BandwidthDesc"] = "Limite a velocidade de cópia para não saturar a rede (0 = Ilimitado)",
        ["SecurityPrivacy"] = "SEGURANÇA E PRIVACIDADE", ["AccessPin"] = "PIN de Acesso", ["PinWatermark"] = "Defina um PIN numérico",
        ["PinDesc"] = "Proteja a interface com uma senha", ["LockOnMinimize"] = "Bloquear ao minimizar",
        ["EncryptionKey"] = "Chave de Criptografia Mestra", ["EncryptionKeyWatermark"] = "Sua chave global", ["EncryptionDesc"] = "Sugerida como padrão para novos jobs seguros",
        ["ExternalNotifications"] = "NOTIFICAÇÕES EXTERNAS (WEBHOOKS & SMTP)", ["WebhookUrl"] = "Webhook URL",
        ["WebhookUrlWatermark"] = "https://discord.com/api/webhooks/...", ["SmtpServer"] = "Servidor SMTP",
        ["SmtpHostWatermark"] = "smtp.gmail.com", ["Port"] = "Porta", ["DestEmail"] = "E-mail Destino",
        ["DestEmailWatermark"] = "alertas@email.com", ["EnableSmtp"] = "Ativar E-mail", ["NotifyOnSuccess"] = "Notificar Sucessos", ["NotifyOnError"] = "Notificar Erros",
        ["AutomationSystem"] = "AUTOMAÇÃO E SISTEMA", ["StartWithWindows"] = "Iniciar com o Windows", ["StartWithWindowsDesc"] = "Abrir automaticamente ao ligar o computador",
        ["CloseToTray"] = "Fechar para a Bandeja (System Tray)", ["CloseToTrayDesc"] = "Manter o AutoFlow rodando ao fechar a janela principal",
        ["MaintenanceData"] = "MANUTENÇÃO E DADOS", ["LogRetention"] = "Retenção de Logs", ["LogRetentionDesc"] = "Dias para manter os registros no histórico",
        ["DatabaseSize"] = "Tamanho: {0}", ["ClearNow"] = "Limpar Agora", ["OptimizeDatabase"] = "Otimizar Banco",
        ["VisualLanguage"] = "VISUAL E IDIOMA", ["InterfaceTheme"] = "Tema da Interface", ["SystemLanguage"] = "Idioma do Sistema",
        ["GlassOpacity"] = "Opacidade do Efeito Vidro (Mica/Acrylic)", ["DiscardChanges"] = "Descartar Alterações",
        ["ConfigureAutomation"] = "Configurar Fluxo", ["AutomationRules"] = "Defina as regras, filtros e destinos para o fluxo de dados",
        ["General"] = "Geral", ["Performance"] = "Performance", ["Notifications"] = "Notificações", 
        ["Maintenance"] = "Manutenção", ["About"] = "Sobre", ["AboutAutoFlow"] = "Sobre o AutoFlow",
        ["GeneralSettings"] = "Geral", ["SecuritySettings"] = "Segurança",
 ["Filters"] = "Filtros", ["Schedule"] = "Agenda", ["Security"] = "Segurança", ["Advanced"] = "Avançado",
        ["JobName"] = "Nome do Fluxo", ["SourcePath"] = "Caminho de Origem", ["DestPath"] = "Caminho de Destino", ["WorkMode"] = "Modo de Trabalho",
        ["FileConflicts"] = "Conflitos de Arquivo", ["IncludeExtensions"] = "Extensões (Inclusão)", ["IgnorePatterns"] = "Padrões a Ignorar",
        ["RegexExpression"] = "Expressão Regular (REGEX)", ["WatcherConfigs"] = "CONFIGURAÇÕES DO WATCHER", ["DetectionMethod"] = "Método de Detecção",
        ["StabilizationTime"] = "Tempo de Estabilização", ["ScheduleType"] = "Tipo de Agendamento", ["RepeatOnDays"] = "Repetir nos dias:",
        ["Sun"] = "D", ["Mon"] = "S", ["Tue"] = "T", ["Wed"] = "Q", ["Thu"] = "Q", ["Fri"] = "S", ["Sat"] = "S",
        ["ExecutionTime"] = "Horário de Execução", ["DataProtection"] = "PROTEÇÃO DE DADOS (AES-256)", ["EncryptionKeyLabel"] = "Chave de Criptografia",
        ["JobWebhooks"] = "WEBHOOKS DE FLUXO", ["SimulationSummary"] = "RESUMO DA SIMULAÇÃO", ["FilesIdentified"] = "Arquivos Identificados",
        ["DataVolume"] = "Volume de Dados", ["SimulationSuccess"] = "A simulação foi concluída com sucesso.",
        ["Simulate"] = "Simular (Preview)", ["NewDirectCopyTitle"] = "Novo Fluxo Direto", ["NewWatchFolderTitle"] = "Novo Fluxo Ativo",
        ["Save"] = "Salvar", ["Cancel"] = "Cancelar", ["ProcessSubfolders"] = "Processar Subpastas", ["SmartSyncLabel"] = "Smart Sync (Pular idênticos)",
        ["VerifyHashLabel"] = "Validar Integridade Pós-Cópia (Hash)", ["ClearPreview"] = "Limpar Preview", ["SaveAutomation"] = "Salvar Fluxo",
        ["AuditHistory"] = "Auditoria e Histórico", ["ForenseTracking"] = "Rastreamento forense de todas as operações de arquivos",
        ["ExportCsv"] = "Exportar CSV", ["OpDetails"] = "DETALHES DA OPERAÇÃO", ["File"] = "Arquivo", ["Destination"] = "Destino",
        ["Size"] = "Tamanho", ["Duration"] = "Duração", ["EngineLogs"] = "Logs do Engine", ["SelectEntry"] = "Selecione uma entrada para ver os detalhes",
        ["SearchWatermark"] = "Buscar arquivo ou detalhe...", ["Time"] = "Hora", ["Origin"] = "Origem", ["OpenSourceFolder"] = "Abrir Pasta de Origem",
        ["OpenDestFolder"] = "Abrir Pasta de Destino", ["ClearHistory"] = "Limpar Todo o Histórico", ["Copied"] = "COPIADO",
        ["Moved"] = "MOVIDO", ["Ignored"] = "IGNORADO", ["FailedStatus"] = "FALHA", ["Zipped"] = "ZIPADO", ["Cancelled"] = "CANCELADO",
        ["SidebarAutomation"] = "Fluxos", ["SidebarAudit"] = "Auditoria", ["AutomationHub"] = "Central de Fluxos",
        ["ActiveBadge"] = "{0} Ativos", ["QueueReady"] = "Pronto", ["AutomationDesc"] = "Orquestre e gerencie seus fluxos de dados",
        ["StopAllTip"] = "Encerrar Tudo", ["Active"] = "Ativos", ["Pending"] = "Pendentes", ["Watchers"] = "Watchers",
        ["SearchJobsWatermark"] = "Pesquisar fluxos...", ["SelectedCount"] = "{0} selecionados", ["RealTimeProcessing"] = "PROCESSAMENTO EM TEMPO REAL",
        ["ConfiguredTasks"] = "SEUS FLUXOS", ["RunTip"] = "Iniciar", ["StopTip"] = "Parar", ["EditTip"] = "Editar", ["DeleteTip"] = "Excluir",
        ["OriginLabel"] = "ORIGEM:", ["DestLabel"] = "DESTINO:", ["Frequency"] = "FREQUÊNCIA", ["SpeedLabel"] = "VELOCIDADE", ["LiveTerminal"] = "TERMINAL LIVE",
        ["Processing"] = "Processando...", ["Idle"] = "Ocioso", ["Queued"] = "Na Fila...", ["NewDirectCopy"] = "Novo Fluxo",
        ["NewWatchFolder"] = "Nova Watch", ["JobNameWatermark"] = "Ex: Backup de Documentos", ["Browse"] = "Procurar",
        ["ExtensionsWatermark"] = ".jpg, .png, .pdf", ["IgnoreWatermark"] = "node_modules, temp", ["RegexWatermark"] = "Ex: ^[0-9]{4}.*",
        ["OpenApp"] = "Abrir AutoFlow", ["Exit"] = "Sair", ["SuccessBadge"] = "OK", ["IgnoredBadge"] = "IGN", ["ErrorBadge"] = "ERR", ["SmtpEmailHeader"] = "SMTP / E-mail",
        ["JobStarted"] = "Fluxo '{0}' iniciado.", ["RetryMode"] = " [MODO RETRY]", ["PreScriptFailed"] = "Pre-script falhou.",
        ["SourceNotFound"] = "Pasta de origem não encontrada: {0}", ["JobError"] = "Erro no Fluxo", ["JobFailedSourceNotFound"] = "Fluxo '{0}' falhou: Origem não encontrada.",
        ["StartingFile"] = "Iniciando: {0}", ["SuccessFile"] = "Sucesso: {0}", ["ErrorFile"] = "ERRO: {0}",
        ["FilterIgnored"] = "Filtro de exclusão.", ["JobFinished"] = "Fluxo Finalizado: {0}.", ["JobCompleted"] = "Fluxo Concluído",
        ["FilesFailed"] = "{0} arquivos falharam.", ["UserCancelled"] = "Fluxo '{0}' cancelado pelo usuário.", ["UserCancelledOp"] = "Operação cancelada.",
        ["CriticalError"] = "Erro Crítico", ["CriticalErrorJob"] = "Erro crítico no fluxo '{0}': {1}", ["PostScriptFailed"] = "Post-script falhou.",
        ["IntegrityFailed"] = "Falha na verificação de integridade.", ["ZipCreationFailed"] = "Falha ao criar arquivo ZIP: {0}",
        ["RetentionOldDeleted"] = "Retenção: Arquivo antigo excluído '{0}'.", ["RetentionExpiredDeleted"] = "Retenção: Arquivo expirado excluído '{0}'.",
        ["RetentionFailed"] = "Falha ao aplicar política de retenção: {0}", ["SmartSyncDetail"] = "SmartSync", ["StartingJobLog"] = "Iniciando Fluxo: {0}",
        ["PreviewErrorSourceNotFound"] = "[ERRO] Diretório de origem não encontrado: {0}", ["PreviewIgnored"] = "[IGNORADO] {0}",
        ["PreviewIgnoredSmartSync"] = "[IGNORADO - SMART SYNC] {0}", ["PreviewIgnoredConflict"] = "[IGNORADO - CONFLITO] {0}",
        ["PreviewOverwrite"] = "[SOBRESCREVER] {0}", ["PreviewRename"] = "[RENOMEAR] {0}", ["PreviewCopy"] = "[COPIAR] {0}", ["PreviewMove"] = "[MOVER] {0}",
        ["RamUsageFormat"] = "{0} GB / {1} GB", ["TimeSavedFormat"] = "{0}h {1}m", ["SchedulerLoopError"] = "Erro no loop do agendador: {0}",
        ["DailyMaintenanceSuccess"] = "Manutenção diária concluída com sucesso.", ["DailyMaintenanceError"] = "Erro na manutenção diária: {0}",
        ["DailySummaryName"] = "Resumo Diário", ["InXDays"] = "em {0} dias", ["InXHours"] = "em {0}h", ["InXMinutes"] = "em {0}min",
        ["SupportTitle"] = "Apoie o Desenvolvedor", ["SupportPixLabel"] = "Chave Pix (Brasil)", ["SupportCoffeeLabel"] = "Buy Me a Coffee", ["SupportCopyPix"] = "Copiar Chave",
        ["Donate"] = "Doar",
        
        // Organization (Blueprint)
        ["Organization"] = "Blueprint",
        ["Scaffolding"] = "Estrutura",
        ["ScaffoldingDesc"] = "Criar subpastas automaticamente",
        ["Renaming"] = "Renomeação Inteligente",
        ["RenamingDesc"] = "Padronizar nomes usando tokens",
        ["FolderBlueprint"] = "Blueprint de Pasta",
        ["FileOrganization"] = "Organização de Arquivos",
        ["FolderStructure"] = "Estrutura de Pastas",
        ["NewFileBlueprint"] = "Novo Blueprint de Arquivo",
        ["NewFolderBlueprint"] = "Novo Blueprint de Pasta",
        ["AddFolder"] = "Adicionar Pasta",
        ["RenameTemplateLabel"] = "Template de Renomeação",
        ["TokensAvailable"] = "Tokens: {Date}, {JobName}, {Counter}, {001}",
        ["TokensFolderDesc"] = "Especiais: {FolderName}, {Parent}, {Ano}, {Mes}",
        ["TokensFileDesc"] = "Especiais: {FileName}, {Ext}, {Date}",
        ["TokenOriginal"] = "Nome Original",
        ["TokenParent"] = "Pasta Pai",
        ["TokenDate"] = "Data Atual",
        ["TokenYear"] = "Ano Atual",
        ["TokenMonth"] = "Mês Atual",
        ["TokenCounter"] = "Contador",
        ["Token001"] = "Contador (001)",
        ["TokenGuid"] = "ID Único",
        ["PresetDate"] = "Data e Nome",
        ["PresetCounter"] = "Sequencial",
        ["PresetSnake"] = "Limpeza (snake_case)",
        ["BeforeAfter"] = "Transformação",
        ["InternalStructure"] = "Estrutura Interna (O que criar dentro?)",
        ["IdentityHeader"] = "Identidade (Como renomear?)",
        ["QuickStyles"] = "Estilos Rápidos",
        ["MagicPresets"] = "Sugestões Prontas",
        ["TokenDay"] = "Dia Atual",
        ["PresetCamel"] = "Programação (camelCase)",
        ["RegexRemoveNumbers"] = "Remover Números",
        ["RegexCleanSpecial"] = "Limpar Especiais",
        ["RegexExtractDate"] = "Extrair Data",
        ["RegexRemoveParentheses"] = "Remover Parênteses",
        ["InvalidChars"] = "Caracteres Inválidos",
        ["ToolboxTokens"] = "Tokens",
        ["ToolboxStyles"] = "Estilos",
        ["ToolboxRegex"] = "Regex",
        ["ToolboxCleanup"] = "Limpeza",
        ["ToolboxSubstrings"] = "Substrings",
        ["TakeLabel"] = "Pegar primeiros N",
        ["SkipLabel"] = "Pular primeiros N",
        ["CleanDoubleSpaces"] = "Remover Espaços Duplos",
        ["CleanSymbols"] = "Limpar Símbolos",
        ["SpacesToUnderscore"] = "Espaços -> Sublinhados",
        ["StressTestDesc"] = "Exemplo Complexo (Teste de Estresse)",
        ["OriginalPath"] = "ORIGEM",
        ["ResultPath"] = "DESTINO",
        ["MagicTools"] = "FERRAMENTAS MÁGICAS",
        ["SmartToolbox"] = "CAIXA DE FERRAMENTAS",
        ["ConfigureCounter"] = "Configurar Contador:",
        ["ZerosPadding"] = "Zeros (Padding)",
        ["InsertCounter"] = "Inserir Contador",
        ["StylesGuideTitle"] = "Guia de Estilos e Limpeza",
        ["RegexTipsTitle"] = "Dicas de Regex Avançado",
        ["RegexTutorial"] = "Regex: \\d (número), \\w (letra), [^abc] (exceto abc). Ex: \\d+ remove todos números.",
        ["RegexTips"] = "Dicas: ( ) cria grupos, $1 usa o primeiro grupo. Modificadores regex substituem TODAS as ocorrências por padrão.",
        ["RegexAdvancedHelp"] = "Expressões Regulares permitem manipulações complexas:\n\n• GRUPOS: Use ( ) para capturar partes do nome.\n• RETRO-REFERÊNCIA: Use $1, $2 para reinserir partes capturadas.\n• QUANTIFICADORES:\n  + (uma ou mais vezes)\n  * (zero ou mais vezes)\n  ? (opcional)\n• CLASSES:\n  \\d (qualquer número)\n  \\w (letras e números)\n  \\s (espaços)\n  . (qualquer caractere)",
        ["StylesAdvancedHelp"] = "Transformadores de Identidade:\n\n• CASE: Mude para MAIÚSCULA, minúscula ou Title Case.\n• PROGRAMAÇÃO: Converta para camelCase ou snake_case para compatibilidade com código.\n• LIMPEZA: Use ':clean' para remover símbolos especiais e manter um nome 'puro'.\n• SUBSTRINGS:\n  TAKE (pega os primeiros N caracteres)\n  SKIP (pula os primeiros N caracteres)",
        ["EnableOrganization"] = "Ativar Organização",
        ["BlueprintDesc"] = "Defina regras para organizar pastas e arquivos no local",
        ["BlueprintHub"] = "Centro de Blueprint",
        ["NewBlueprintTitle"] = "Configurar Automação",
        ["NewFileBlueprintTitle"] = "Nova Organização de Arquivo",
        ["NewFolderBlueprintTitle"] = "Nova Estrutura de Pasta",
        ["PathToOrganize"] = "Caminho a Organizar",
        ["SidebarBlueprint"] = "Blueprint",
        ["EnableAutoScaffolding"] = "Monitoramento Real (Auto-Scaffolding)",
        ["AutoScaffoldingTip"] = "Injeta automaticamente a estrutura de pastas quando um novo diretório é criado ou renomeado.",
        ["EnableAutoRenaming"] = "Renomeação Automática",
        ["AutoRenamingTip"] = "Renomeia automaticamente os novos arquivos que entram nesta pasta baseado no template.",
        ["NoWatchers"] = "Nenhuma pasta monitorada encontrada.",
        ["NoTransfers"] = "Nenhum fluxo de transferência configurado.",
        ["NoIncidents"] = "Nenhum incidente registrado. Tudo funcionando bem!",
        ["NoSystemLogs"] = "Nenhum evento de sistema registrado.",
        ["NoFileBlueprints"] = "Nenhum modelo de organização de arquivos.",
        ["NoFolderBlueprints"] = "Nenhum modelo de estrutura de pastas configurado.",
    };

    private void CreateDefaultFile(string path, string culture)
    {
        var dict = GetDefaults(culture);
        SaveTranslations(path, dict);
    }
}
